# Generated by Django 4.1.7 on 2023-08-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="acc_no",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="balance",
        ),
        migrations.AddField(
            model_name="profile",
            name="pan_card",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
