# Generated by Django 4.1.7 on 2023-08-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_profile_acc_no_remove_profile_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mobile_no",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pan_card",
            field=models.CharField(max_length=20),
        ),
    ]
