# Generated by Django 4.1.7 on 2023-08-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_profile_mobile_no_alter_profile_pan_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_no",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
