# Generated by Django 4.1.7 on 2023-08-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_profile_account_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1.0, max_digits=5
            ),
            preserve_default=False,
        ),
    ]
