# Generated by Django 4.1.7 on 2023-08-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_history_alter_profile_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mobile_no",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
