# Generated by Django 4.1.7 on 2023-08-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_profile_mobile_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="id",
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile_no",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
