# Generated by Django 4.1.7 on 2023-08-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_profile_id_alter_profile_mobile_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile_no",
            field=models.CharField(max_length=10),
        ),
    ]
